const names = [
  'The Careless Crusaders',
  'The Major Dingos',
  'The Grim Beluga Whales',
  'The United Honey Badgers',
  'The Clever Droids',
  'The Mysterious Furies',
  'The Fast Saints',
  'The Potent Wolverines',
  'The Brutal Seals',
  'The Enchanted Furies',
  'The Mad Honey Badgers',
  'The Fantastic Raccoons',
  'The Black Droids',
  'The Great Arrows',
  'The Spirit Braves',
  'The Wise Yetis',
  'The Freedom Nationals',
  'The Determined Shades',
  'The Naughty Chimps',
  'The Deadly Spartans',
  'The Heavenly Terrors',
  'The Courageous Snowstorms',
  'The Mysterious Swans',
  'The Rough Scorpions',
  'The Mystery Beavers',
  'The Brute Cubs',
  'The Heavenly Honey Badgers',
  'The White Miracles',
  'The Pure Gophers',
  'The Major Monkeys',
  'The Hidden Nationals',
  'The Loyal Suns',
  'The Crazy Soldiers',
  'The Mystery Striders',
  'The Ancient Titans',
  'The Powerful Lizards',
  'The Regal Terrors',
  'The Flawless Horses',
  'The Rapid Bruisers',
  'The Daring Honey Badgers',
  'The Creative Gargoyles',
  'The Naughty Pumas',
  'The Regal Orcs',
  'The Enchanted Leopards',
  'The Ancient Terrors',
  'The Bold Llamas',
  'The Hard Penguins',
  'The Golden Pigs',
  'The Hard Beasts',
  'The Infamous Krakens',
  'The White Deer',
  'The Angry Riddles',
  'The Calm Giants',
  'The Colossal Tornadoes',
  'The Haunting Griffins',
  'The Fiery Porcupines',
  'The Quick Aliens',
  'The Glorious Lizards',
  'The Merry Penguins',
  'The Awesome Pelicans',
  'The Infamous Broncos',
  'The Courageous Angels',
  'The Rough Monkeys',
  'The Powerful Dogs',
  'The Merry Demons',
  'The Regal Nationals',
  'The Hidden Shadows',
  'The Fiery Panthers',
  'The Classic Legends',
  'The Infamous Parrots',
  'The Terrific Swallows',
  'The Flawless Pandas',
  'The Strong Rhinos',
  'The Clever Lobsters',
  'The Golden Claws',
  'The Crazy Warhogs',
  'The Fearless Gnomes',
  'The Wicked Bottle Rockets',
  'The Valiant Pigs',
  'The Glorious Mythics',
  'The True Cavaliers',
  'The Crazy Hounds',
  'The Wicked Llamas',
  'The Bold Broncos',
  'The Angry Orcs',
  'The Red Vikings',
  'The Hidden Boomers',
  'The Loyal Grizzlies',
  'The Spectacular Rhinos',
  'The True Crocs',
  'The Tough Bottle Rockets',
  'The Colossal Cubs',
  'The Haunting Bulldogs',
  'The Freedom Horses',
  'The Silver Rovers',
  'The Awesome Robots',
  'The True Crickets',
  'The Creative Toads',
  'The Quiet Doves',
  'The Angry Saints',
];

export default function getRandomTeamName() {
  return names[Math.floor(Math.random() * names.length)];
}
